### ISSUE TITLE
Request for a readme for running the project...

### ISSUE THREAD

**Issue by NitinDatta8** [CVerRobin/wheatdetection#1]
Hi @CVerRobin , 
A readme file addressing how to run this project might be very helpful...
Thanks in advance

**Comment by wuxinwang1997** [comment]
> Hi @CVerRobin ,
> A readme file addressing how to run this project might be very helpful...
> Thanks in advance

Just see my develop branch's readme. If I it's functions can run without error, I'll update master branch.

**Comment by tianyu-sz** [comment]
训练的命令可以，测试的不行。test_net.py没加载权重，我看其他分支有处理的，要不要合并下

**Comment by tianyu-sz** [comment]
命令传入参数的写法，有点怪。一般是 --weight /path/to/weight 形式。

**Comment by wuxinwang1997** [comment]
> 命令传入参数的写法，有点怪。一般是 --weight /path/to/weight 形式。

这个是使用的

**Comment by wuxinwang1997** [comment]
> 训练的命令可以，测试的不行。test_net.py没加载权重，我看其他分支有处理的，要不要合并下

你看看master分支的test_net.py移植过来能不能用

**Comment by clw5180** [comment]
请问kaggle分数能到多少
